version: '3.7'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: me
      MONGO_INITDB_ROOT_PASSWORD: hackme

  dev:
    build:
      context: .
      target: dev  # Or prod for testing production version
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://me:hackme@mongo/
      MONGO_DBNAME: dev
      MONGO_TESTDBNAME: test
    volumes:
      - ./api:/opt/restapi/api:ro
